### PR TITLE
remove AVX2 compilations

### LINKED ISSUE #7: Package does not work on non-AVX2 machines
Issue: 
The bitshuffle package always tries to run AVX2 instructions, whether the machine is AVX2-capable or not.

ie.
```bash
$ conda install bitshuffle
$ python -c "import bitshuffle; print(bitshuffle.using_AVX2())"
True
$ grep avx2 /proc/cpuinfo
$
```

I asked in conda-forge gitter and [conda-forge packages target](https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/db4af063875bf7c9c321e8bac72ef21008191c75/recipe/conda_build_config.yaml#L25) the [nocona](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) architecture ("_Improved version of Intel Pentium 4 CPU with 64-bit extensions, MMX, SSE, SSE2 and SSE3 instruction set support_"), which excludes avx2 instructions.

I therefore suspect the solution is to remove the [custom avx2 build instructions from build.sh](https://github.com/conda-forge/bitshuffle-feedstock/blob/master/recipe/build.sh#L5-L16)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
apipkg                    1.5                        py_0    conda-forge
argh                      0.26.2                py36_1001    conda-forge
arrow                     0.15.5                   py36_0    conda-forge
atk                       2.32.0               haf93ef1_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
biopython                 1.73             py36h14c3975_0    conda-forge
bitshuffle                0.3.5            py36hdbb4d8e_3    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.1.1                      py_0    conda-forge
blessings                 1.7                   py36_1000    conda-forge
bpython                   0.18                     py36_0    conda-forge
bump2version              0.5.11                   py36_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.11.28       py36h9f0ad1d_1    conda-forge
cffi                      1.14.0           py36hd463f26_0    conda-forge
cfgv                      3.0.0                      py_0    conda-forge
chardet                   3.0.4           py36h9f0ad1d_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
cmarkgfm                  0.4.2            py36h516909a_2    conda-forge
colorama                  0.4.3                      py_0    conda-forge
colorlog                  4.1.0            py36h9f0ad1d_2    conda-forge
conda                     4.8.3            py36h9f0ad1d_0    conda-forge
conda-package-handling    1.6.0            py36h516909a_1    conda-forge
cookiecutter              1.7.0                      py_0    conda-forge
cryptography              2.8              py36h45558ae_2    conda-forge
curtsies                  0.3.1                    py36_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
cython                    0.29.15          py36h831f99a_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
dials-data                2.0.0                     dev_0    <develop>
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.16             py36h9f0ad1d_1    conda-forge
drmaa                     0.7.9                   py_1000    conda-forge
editdistance              0.5.3            py36he1b5a44_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
execnet                   1.7.1                      py_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fast-dp                   1.6.2                     dev_0    <develop>
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
future                    0.18.2           py36h9f0ad1d_1    conda-forge
gdk-pixbuf                2.38.2               h3f25603_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py36hd3ed26a_1003    conda-forge
gobject-introspection     1.58.2          py36h5503ade_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graypy                    2.0.0                      py_0    conda-forge
greenlet                  0.4.15           py36h8c4c3a4_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gtk2                      2.24.32              h90f3771_0    conda-forge
h5py                      2.10.0          nompi_py36h513d04c_102    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
hdf5-external-filter-plugins 0.1.0                         0    conda-forge
hdf5-external-filter-plugins-bitshuffle 0.1.0                hee945a8_0    conda-forge
hdf5-external-filter-plugins-bzip2 0.1.0                hc6ef4cb_0    conda-forge
hdf5-external-filter-plugins-lz4 0.1.0                hee945a8_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
identify                  1.4.11                     py_0    conda-forge
idna                      2.9                        py_1    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0            py36h9f0ad1d_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
importlib_resources       1.3.1                    py36_0    conda-forge
ispyb                     5.6.0                     dev_0    <develop>
jeepney                   0.4.3                      py_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jira                      2.0.0                    pypi_0    pypi
jiradls                   0.16                      dev_0    <develop>
jpeg                      9c                h14c3975_1001    conda-forge
junit-xml                 1.8                        py_0    conda-forge
keyring                   21.1.1                   py36_0    conda-forge
kiwisolver                1.1.0            py36hdb11119_1    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0           7_h6e990d7_netlib    conda-forge
libcblas                  3.8.0           7_h6e990d7_netlib    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libglu                    9.0.0             hf484d3e_1000    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libgpg-error              1.36                 he1b5a44_0    conda-forge
libgsasl                  1.8.0             h19a2143_1004    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0           7_h6e990d7_netlib    conda-forge
libntlm                   1.4               h516909a_1002    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.11.3               h8b12597_0    conda-forge
librdkafka                1.3.0                hb2b7465_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py36h8c4c3a4_1    conda-forge
matplotlib-base           3.0.3            py36h5f35d83_1    conda-forge
mock                      3.0.5            py36h9f0ad1d_1    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
mrcfile                   1.1.2                      py_1    conda-forge
msgpack-python            0.6.2            py36hc9558a2_0    conda-forge
mysql-connector-c         6.1.11            hc9bbbdd_1005    conda-forge
mysql-connector-python    8.0.18           py36hfcd16c1_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
nodeenv                   1.3.5                      py_0    conda-forge
numpy                     1.16.5           py36h95a1406_0    conda-forge
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
orderedset                2.0.3            py36h516909a_1    conda-forge
packaging                 20.1                       py_0    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
pathlib2                  2.3.5            py36h9f0ad1d_1    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pbr                       5.4.4                    pypi_0    pypi
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.0.0            py36h8328e55_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
poyo                      0.5.0                      py_0    conda-forge
pre-commit                2.2.0            py36h9f0ad1d_0    conda-forge
procrunner                1.1.0                     dev_0    <develop>
prompt-toolkit            3.0.4                    pypi_0    pypi
protobuf                  3.11.3           py36he1b5a44_0    conda-forge
psutil                    5.7.0            py36h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pycosat                   0.6.3           py36h8c4c3a4_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyjwt                     1.7.1                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyrtf                     0.45                       py_2    conda-forge
pysocks                   1.7.1            py36h9f0ad1d_1    conda-forge
pytest                    4.6.4                    py36_0    conda-forge
pytest-forked             1.1.2                      py_0    conda-forge
pytest-mock               1.13.0                   py36_0    conda-forge
pytest-sugar              0.9.2                      py_0    conda-forge
pytest-watch              4.1.0                 py36_1000    conda-forge
pytest-xdist              1.31.0                     py_0    conda-forge
python                    3.6.10          h9d8adfe_1009_cpython    conda-forge
python-confluent-kafka    1.3.0            py36h516909a_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py36h8c4c3a4_1    conda-forge
pyzmq                     17.1.2          py36h6afc9c9_1001    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
readme_renderer           24.0                       py_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
requests-toolbelt         0.9.1                      py_0    conda-forge
ruamel_yaml               0.15.80         py36h516909a_1000    conda-forge
scikit-learn              0.20.2          py36_blas_openblashebff5e3_1400  [blas_openblas]  conda-forge
scipy                     1.2.1           py36_blas_openblash1522bff_0  [blas_openblas]  conda-forge
scons                     3.1.2                    py36_0    conda-forge
screen19                  0.207                     dev_0    <develop>
secretstorage             3.1.2            py36h9f0ad1d_1    conda-forge
setuptools                46.0.0           py36h9f0ad1d_2    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    1.8.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
stomp.py                  4.1.22                     py_0    conda-forge
tabulate                  0.8.6                      py_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
tox                       2.8.1                    py36_0    conda-forge
tqdm                      4.23.4                     py_0    conda-forge
twine                     3.1.1                    py36_0    conda-forge
urllib3                   1.25.7           py36h9f0ad1d_1    conda-forge
urwid                     2.1.0            py36h516909a_0    conda-forge
virtualenv                16.7.5                     py_0    conda-forge
watchdog                  0.10.2                   py36_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
workflows                 1.7.2                     dev_0    <develop>
wxpython                  4.0.6            py36h8f66242_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zocalo                    0.6.2                     dev_0    <develop>
zstd                      1.4.4                h3b9ef0a_1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
       user config file : /home/wra62962/.condarc
 populated config files : /scratch/wra62962/files/dials/conda_base/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.6.10.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.17
       base environment : /scratch/wra62962/files/dials/conda_base  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /scratch/wra62962/files/dials/conda_base/pkgs
                          /home/wra62962/.conda/pkgs
       envs directories : /scratch/wra62962/files/dials/conda_base/envs
                          /home/wra62962/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.10 Linux/3.10.0-1062.12.1.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 1013292:1013292
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Build package without AVX2 on any platforms. Possibly resolves #7

### CODE REVIEW

**Comment by Anthchirp** [comment]
skipping re-render, as this will likely need to be done shortly to fix Python 3.8 builds anyway

**Comment by xmnlab** [comment]
@Anthchirp thanks for working on that.

I don't have any problems with this change at all, but could you provide more information about why you want to remove AVX2 compilations?

I create this recipe based on an old version of this script: https://github.com/apache/kudu/blob/master/thirdparty/build-definitions.sh#L554

If you need a package without avx2 support building .. maybe we could build one version without avx2 and another version using avx2, using `outputs` section*. So for example, this feedstock could generate bitshuffle and bitshuffle-avx2

here there is an example about how to use outputs: https://github.com/conda-forge/pre-commit-feedstock/blob/master/recipe/meta.yaml#L19

what do you think about this alternative?

* https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section

**Comment by Anthchirp** [comment]
I don't know. My primary motivation is that we have a set of pre-AVX2 computers we want to install the package on, and at the moment they get an AVX2-compiled version which does not work. When I asked in conda-forge gitter I was told about the default supported architecture (see #7), which this PR moves to.

In an ideal world the upstream package should probably check if the host is AVX2-capable and fall back to non-AVX2 code if it is not, and then we could always compile it with included support.

I don't know if `outputs` can be useful here. Maybe @conda-forge/core can advise?

**Comment by jakirkham** [comment]
My guess is the default `CFLAGS` are probably fine for both use cases, but could be wrong.

cc @isuruf (who knows more on this subject)

File: recipe/build.sh [hunk 1]
```diff
@@ -2,41 +2,19 @@
...
-    objcopy --redefine-syms=renames.txt $tmp_obj $dst_obj
-  else
-    mv $tmp_obj $dst_obj
-  fi
-  to_link="$to_link $dst_obj"
-done
+tmp_obj=bitshuffle_default_tmp.o
+dst_obj=bitshuffle_default.o
+
+${CC:-gcc} $CFLAGS $EXTRA_CFLAGS -std=c99 -I$PREFIX/include -DNDEBUG -c \
```
Comment (jakirkham) [inline recipe/build.sh]: I think this can be simplified since `$CC` is always defined.

```suggestion
$CC $CFLAGS $EXTRA_CFLAGS -std=c99 -I$PREFIX/include -DNDEBUG -c \
```

File: recipe/build.sh [hunk 2]
```diff
@@ -2,41 +2,19 @@
...
+  "src/bitshuffle_core.c" \
+  "src/bitshuffle.c" \
+  "src/iochain.c"
+
+# Merge the object files together to produce a combined .o file.
+ld -r -o $tmp_obj bitshuffle_core.o bitshuffle.o iochain.o
```
Comment (jakirkham) [inline recipe/build.sh]: We have `LDFLAGS` too. Would be good to add them here. Though don't know enough about what this feedstock is doing to suggest how to do that atm. @xmnlab do you have thoughts on how we do this? 🙂

Comment (xmnlab) [reply recipe/build.sh]: actually I am not an expert here :) I just prepared this using a script on kudu repo to build bitshuffle :) ... so any recommendation would be very appreciated :)

PS: I created this package because I was trying to create a kudu conda package ... but I needed to stop :(

**Comment by xmnlab** [comment]
@Anthchirp I just merged the PR. I will open an issue about the avx2 and another one about the LDFLAGS. also feel free to add yourself as maintainer of this package ;) thanks for working on that!

File: recipe/build.sh [hunk 3]
```diff
@@ -2,41 +2,19 @@
...
-    objcopy --redefine-syms=renames.txt $tmp_obj $dst_obj
-  else
-    mv $tmp_obj $dst_obj
-  fi
-  to_link="$to_link $dst_obj"
-done
+tmp_obj=bitshuffle_default_tmp.o
+dst_obj=bitshuffle_default.o
+
+$CC $CFLAGS $EXTRA_CFLAGS -std=c99 -I$PREFIX/include -DNDEBUG -c \
```
Comment (jakirkham) [inline recipe/build.sh]: Where is `$EXTRA_CFLAGS` coming from?

File: recipe/build.sh (hunk 2 above)
Comment (jakirkham) [reply recipe/build.sh]: Yeah I don't know enough about what is happening in this script to advise. @isuruf, do you have thoughts? 😉

**Comment by Anthchirp** [comment]
Just seen, and updated PR #9, thank you.
Happy to be added as maintainer if you like.

File: recipe/build.sh (hunk 3 above)
Comment (xmnlab) [reply recipe/build.sh]: thanks for catching this up. probably something we can just remove (https://github.com/apache/kudu/blob/master/thirdparty/build-definitions.sh#L26)
